version: '3.4'

services:
  searchapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6001:80"

  simonvosstask:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6002:80"

